[tools]
node = "22"
"npm:@openai/codex" = "latest"
"npm:@sentry/cli" = "latest"
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
"npm:sqlite-vec" = "latest"
bun = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:svgo" = "latest"
"npm:browse" = "latest"
"npm:@microsoft/rush" = "latest"
